_target_: src.datamodules.imagenet_vqa_json.VQADataModule

data_dir: "/data/data/matt/learning-to-learn-concepts/outputs/composition_04272023/none_with_emb_without_multires"
json_dir: ${data_dir}/compositions/compositions_v1_0/proposed/
categories: ["attribute", "relation", "counting", "action"]
batch_size: 1
num_workers: 0
pin_memory: false
