_target_: src.datamodules.imagenet_datamodule_w_outliers.ImageNetDataModule

data_dir: ${data_dir}/imagenet_subsection # data_dir is specified in config.yaml
test_data_dir: ${data_dir}/imagenet_subsection # data_dir is specified in config.yaml
batch_size: 32
train_val_split: [0.8, 0.2]
num_workers: 2
pin_memory: False
num_cls: ${num_cls}
